workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

stages:
  - setup
  - lint

variables:
  POETRY_HOME: $CI_PROJECT_DIR/poetry
  PATH: $POETRY_HOME/bin:$PATH
  POETRY_VIRTUALENVS_PATH: $CI_PROJECT_DIR/.venv
  POETRY_NO_INTERACTION: "true"

poetry:
  stage: setup
  tags:
    - students
  image:
    name: python:3.12-slim
    entrypoint: [""]
  script:
    - apt-get update && apt-get install -y --no-install-recommends curl
    - curl -sSL https://install.python-poetry.org | python3 -
    - poetry install --only dev

pre-commit:
  stage: lint
  tags:
    - students
  script:
    - poetry run pre-commit run --all-files