workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

stages:
  - setup
  - lint

image: python:3.12-slim

poetry:
  stage: setup
  tags:
    - students
  variables:
    POETRY_HOME: $CI_PROJECT_DIR/poetry
    POETRY_NO_INTERACTION: "true"
  script:
    - apt-get update && apt-get install -y --no-install-recommends curl
    - curl -sSL https://install.python-poetry.org | POETRY_HOME=$CI_PROJECT_DIR/poetry python3 -
    - export PATH="$POETRY_HOME/bin:$PATH"
    - poetry config virtualenvs.in-project true
    - poetry install --only dev --no-root
  artifacts:
    expire_in: 1h
    paths:
      - $CI_PROJECT_DIR/.venv
      - $CI_PROJECT_DIR/poetry

pre-commit:
  stage: lint
  tags:
    - students
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends git
    - export PATH="$CI_PROJECT_DIR/poetry/bin:$PATH"
  script:
    - poetry run pre-commit run --all-files