workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

stages:
  - setup
  - lint

image: python:3.12-slim

variables: 
    POETRY_HOME: $CI_PROJECT_DIR/poetry

poetry:
  stage: setup
  tags:
    - students
  variables:
    POETRY_VIRTUALENVS_PATH: $CI_PROJECT_DIR/.venv
    POETRY_NO_INTERACTION: "true"
  script:
    - apt-get update && apt-get install -y --no-install-recommends curl
    - curl -sSL https://install.python-poetry.org | POETRY_HOME=$CI_PROJECT_DIR/poetry python3 -
    - export PATH="$POETRY_HOME/bin:$PATH"
    - poetry install --only dev --no-root

pre-commit:
  stage: lint
  tags:
    - students
  before_script:
    - export PATH="$POETRY_HOME/bin:$PATH"
  script:
    - poetry run pre-commit run --all-files