repos:
  - repo: https://github.com/pycqa/isort/
    rev: 6.0.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--check", "--diff"]

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        args: ["--check", "--diff"]

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        args: ["--no-incremental"]