exclude: "(alembic|__init__.py)"
repos:
  - repo: https://github.com/pycqa/isort/
    rev: 6.0.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--check", "--diff"]

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        args: ["--check", "--diff"]

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==24.12.12
          - flake8-pie==0.16.0

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        args: ["--no-incremental", "--ignore-missing-imports"]
        additional_dependencies:
          - types-aiofiles==24.1.0.20250326