exclude: ^\.venv/

repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort --check --diff .
        language: system
        types: [ python ]
        pass_filenames: false

      - id: black
        name: black
        entry: black --check --diff .
        language: system
        types: [ python ]
        pass_filenames: false

      - id: flake8
        name: flake8
        entry: flake8 .
        language: system
        types: [ python ]
        pass_filenames: false

      - id: mypy
        name: mypy
        entry: mypy .
        language: system
        types: [ python ]
        pass_filenames: false