services:

  nginx:
    container_name: nginx
    image: nginx:alpine
    depends_on:
      - server
    ports:
      - "8080:80"
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./client/static:/usr/share/nginx/html
    networks:
      - mynetwork

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: server
    ports:
      - '8000:8000'
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
