# Базовые настройки Prometheus

global:  # Глобальные параметры сбора метрик
  scrape_interval: 3s  # Интервал опроса метрик (по умолчанию 1m)

scrape_configs:  # Список конфигураций сбора метрик
  - job_name: "server"  # Имя задания для группы таргетов
    static_configs:  # Статическое определение таргетов
      - targets: ["server:8000"]  # Список endpoint'ов для сбора метрик:
                                  # - "server"- имя сервиса в Docker-сети
                                  # - 8000 - порт FastAPI-приложения