"""Rename column

Revision ID: 28064de989fb
Revises: 65534274eb03
Create Date: 2025-04-30 17:11:27.332066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28064de989fb'
down_revision: Union[str, None] = '65534274eb03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers_association', sa.Column('following_id', sa.Integer(), nullable=False))
    op.drop_constraint('followers_association_followed_id_fkey', 'followers_association', type_='foreignkey')
    op.create_foreign_key(None, 'followers_association', 'users', ['following_id'], ['id'])
    op.drop_column('followers_association', 'followed_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers_association', sa.Column('followed_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'followers_association', type_='foreignkey')
    op.create_foreign_key('followers_association_followed_id_fkey', 'followers_association', 'users', ['followed_id'], ['id'])
    op.drop_column('followers_association', 'following_id')
    # ### end Alembic commands ###
