"""unique constraint between columns follower_id and following_id

Revision ID: 5b71b43666a9
Revises: 28064de989fb
Create Date: 2025-04-30 17:27:33.046777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b71b43666a9'
down_revision: Union[str, None] = '28064de989fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_followers', 'followers_association', ['follower_id', 'following_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_followers', 'followers_association', type_='unique')
    # ### end Alembic commands ###
